### ISSUE TITLE
solve.py missing

### ISSUE THREAD

**Issue by mingtaoli** [APMonitor/apm_server#1]
I tried to install apmonitor server locally. However, when I press run button, I got an error as "The requested URL was not found on this server." I found in view_pass.php, there is a line as "url=/cgi-bin/solve.py". However there is no solve.py in my cgi directory or in this git repos. Please check this.

**Comment by APMonitor** [comment]
The way to solve APMonitor locally is to switch to your server "http://127.0.0.1" with the APM command "apm(s,a,'apm.solver','http://127.0.0.1'). The APMonitor server solutions are accessible through the MATLAB or Python scripts found at http://apmonitor.com/wiki/index.php/Main/PythonApp (Python) or http://apmonitor.com/wiki/index.php/Main/MATLAB (MATLAB).

The interface that you reference with solve.py is the web-interface for someone to solve an APM model without Python or MATLAB at https://apmonitor.com/online/view_pass.php I don't make that interface available because the configuration is much more complicated for the setup.

Another option to solve locally is to use Python Gekko (**pip install gekko**) with option `m=GEKKO(remote=False)`. This solves the APM model locally without needing to install a server.
